DROP DATABASE if EXISTS clinica;
CREATE DATABASE clinica CHARACTER SET utf8 COLLATE UTF8_GENERAL_CI;
USE clinica;


CREATE TABLE user (
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT  PRIMARY KEY,
    name VARCHAR(250)  NOT NULL,
    password VARCHAR(250) NOT NULL
);

CREATE TABLE authorizarion (
	id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT UNSIGNED NOT NULL ,
    jwt VARCHAR(250) NOT NULL
);

SELECT * FROM authorizarion;