DROP DATABASE if EXISTS clinica;
CREATE DATABASE clinica CHARACTER SET utf8 COLLATE UTF8_GENERAL_CI;
USE clinica;


CREATE TABLE user (
	id BIGINT UNSIGNED  AUTO_INCREMENT  PRIMARY KEY,
    name VARCHAR(250) UNIQUE NOT NULL,
    password VARCHAR(250) NOT NULL,
    email VARCHAR(250)  NOT NULL,
    img TEXT,
    phone VARCHAR(250)  NOT NULL,
     active BOOLEAN DEFAULT TRUE
);

CREATE TABLE authorizarion (
	id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT UNSIGNED NOT NULL ,
    jwt VARCHAR(250) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES user(id)
);

SELECT * FROM user;
SELECT * FROM authorizarion;