### Actualizar citas   https://clinica-medica-production.up.railway.app/api/v1/
PUT https://clinica-medica-production.up.railway.app/api/v1/appointment/update/
Content-Type: application/json

  "id": 7,
  "id_doctor": 14,
  "id_patient":41,
  "date": "2024-04-04",
  "startTime": "11:30:00"
}



### Crear citass   https://clinica-medica-production.up.railway.app/api/v1/
POST https://clinica-medica-production.up.railway.app/api/v1/appointment/schedule
Content-Type: application/json

{
  "id_doctor": 17,
  "id_patient": 41,
  "date": "2025-05-05",
  "startTime": "13:00",
  "status": "PROGRAMADA"
}

### Reprogramar citas
PATCH https://clinica-medica-production.up.railway.app/api/v1/appointment/reschedule/8
Content-Type: application/json

{
  "newDate": "2025-07-07",
  "newStartTime": "15:00"
}


### Buscar cita por id
GET https://clinica-medica-production.up.railway.app/api/v1/appointment/get_by_id/1
Content-Type: application/json

### Marcar cita como atendida
PATCH https://clinica-medica-production.up.railway.app/api/v1/appointment/markAsAttended/
Content-Type: application/json


### Completar cita por id 
PATCH https://clinica-medica-production.up.railway.app/api/v1/appointment/complete/7



### Cancelar cita por id 
PATCH https://clinica-medica-production.up.railway.app/api/v1/appointment/cancel/1
Content-Type: application/json



### Listar todas las citas por medico y fecha
GET https://clinica-medica-production.up.railway.app/api/v1/appointment/ocuppied-times/8

{
  "date": "2025-02-03",
  "time": [
    "string"
  ]
}


### Listar todas las citas por id 
GET https://clinica-medica-production.up.railway.app/api/v1/appointment/get_by_id/5

### Listar todas las citas por paciente
GET https://clinica-medica-production.up.railway.app/api/v1/appointment/get_all_by_patient/26

### Listar todas las citas por doctor
GET https://clinica-medica-production.up.railway.app/api/v1/appointment/get_all_by_doctor/8

### Listar todas las citas
GET https://clinica-medica-production.up.railway.app/api/v1/appointment/get_all






