### Crear cita    https://clinica-medica-production.up.railway.app/api/v1/
POST https://clinica-medica-production.up.railway.app/api/v1/appointment/schedule
Content-Type: application/json

{
  "id_doctor": ,
  "id_patient": 1,
  "date": "2025-01-01",
  "startTime": "11:00",
  "status": "PROGRAMADA"
}

### Buscar cita por id

GET https://clinica-medica-production.up.railway.app/api/v1/appointment/get_by_id/1
Content-Type: application/json
