### crear clinica https://clinica-medica-production.up.railway.app/api/v1/
POST https://clinica-medica-production.up.railway.app/api/v1/clinic
Content-Type: application/json

{
  "name": "clinica sur",
  "cuit": "22756698",
  "address": "Mitre 116",
  "phone": "224455669",
  "description": "nada",
  "vlinicImage": "string",
  "active": true
}
### Actualizar clinica por id
PUT https://clinica-medica-production.up.railway.app/api/v1/clinic/1
Content-Type: application/json

{
  "name": "clinica norte",
  "cuit": "22756698899",
  "address": "Mitre 1169",
  "phone": "2244556699",
  "description": "nada9",
  "vlinicImage": "string",
  "active": true
}

### Buscar clinica por id
GET https://clinica-medica-production.up.railway.app/api/v1/clinic/1

### Buscar todas las clinicas
GET https://clinica-medica-production.up.railway.app/api/v1/clinic/all

### Patch con id
PATCH https://clinica-medica-production.up.railway.app/api/v1/clinic/avilable/1











