### crear pacientes    https://clinica-medica-production.up.railway.app/api/v1/
POST https://clinica-medica-production.up.railway.app/api/v1/patients/create
Content-Type: application/json

{
  "user": {
    "name": "Julia",
    "dni": "27566982",
    "obraSocial": "atsa",
    "numeroAsociado": "345234",
    "password": "doce123",
    "email": "priscila@gmail.com",
    "phone": "1156897888",
    "img": "imagen2.png"

  },
  "insurer": "atsa"
}

### buscar paciente por id
GET https://clinica-medica-production.up.railway.app/api/v1/patients/search/43



### actualizar paciente
PUT https://clinica-medica-production.up.railway.app/api/v1/patients/update/33
Content-Type: application/json

{
  "name": "Elena",
  "password": "doce",
  "email": "sofi123@gmail.com",
  "social_work": "SALUD TOTAL ",
  "number_associate": "aa123",
  "phone": "11223344",
  "img": "imagen.png",
  "active": true,
  "insurer": "Suim"
}
### faltan datos del user1

###Eliminar paciente
DELETE https://clinica-medica-production.up.railway.app/api/v1/patients/delete/43
Content-Type: application/json

