### crear pacientes    https://clinica-medica-production.up.railway.app/api/v1/
POST https://clinica-medica-production.up.railway.app/api/v1/patients/create
Content-Type: application/json

{
  "user": {
    "id": 0,
    "name": "dafne ewens",
    "dni": "35456899",
    "obraSocial": "swissmedical",
    "numeroAsociado": "8989",
    "password": "45678",
    "email": "dafneewens@gmail.com",
    "phone": "115689477",
    "img": "string",
    "active": true
  },
  "insurer": "string"
}

### buscar paciente por id
GET https://clinica-medica-production.up.railway.app/api/v1/patients/search/58

### actualizar paciente
PUT https://clinica-medica-production.up.railway.app/api/v1/patients/update/33
Content-Type: application/json

{
  "name": "Elena",
  "password": "doce",
  "email": "sofi123@gmail.com",
  "social_work": "SALUD TOTAL ",
  "number_associate": "aa123",
  "phone": "11223344",
  "img": "imagen.png",
  "active": true,
  "insurer": "Suim"
}


###Eliminar paciente
DELETE https://clinica-medica-production.up.railway.app/api/v1/patients/delete/43
Content-Type: application/json