### crear pasientes    https://clinica-medica-production.up.railway.app/api/v1/
POST https://clinica-medica-production.up.railway.app/api/v1/patients/create
Content-Type: application/json

{
  "user": {
    "name": "SOFIA MONSALVE",
    "dni": "3258746254",
    "obraSocial": "SALUD TOTAL ",
    "numeroAsociado": "aa2365",
    "password": "doce",
    "email": "sofi@gmail.com",
    "phone": "1236547802",
    "img": "imagen.png"

  },
  "insurer": "Suim"
}

### buscar pasiente por id
GET https://clinica-medica-production.up.railway.app/api/v1/patients/search/184



### actualizar pasiente
PUT https://clinica-medica-production.up.railway.app/api/v1/patients/update/184
Content-Type: application/json

{
  "social_work": "SUMIMEDICAL2",
  "number_associate": "4569872",
  "phone": "4569874122",
  "insurer": "sura2"
}
### faltan datos del user1
